# Generated by Django 6.0.2 on 2026-03-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_teacherrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='original_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
