# Generated by Django 6.0.2 on 2026-03-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teacherstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_universal',
            field=models.BooleanField(default=False, verbose_name='Доступно всем учителям'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='price_per_lesson',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
