# Generated by Django 6.0.2 on 2026-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_material_file_alter_material_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_universal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='price_per_lesson',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
