# Generated by Django 6.0.2 on 2026-03-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='ID серии'),
        ),
    ]
