# Generated by Django 6.0.4 on 2026-04-19 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lesson_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_homeworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_homeworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('done', 'Проведен'), ('canceled', 'Отменен')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_lessons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher', 'date_time'], name='lesson_teacher_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['student', 'date_time'], name='lesson_student_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', 'date_time'], name='lesson_status_dt_idx'),
        ),
    ]
